Settings:
  awUrl: http://localhost:5600
  prometheusUrl: http://localhost:9090
  prometheusAuth: ""
  excludedWatchers: []
  userId: Phillip
  includeHostname: true
  plugins:
    - "filters"  # This is the only plugin that is enabled by default
