{
 "title": "ActivityWatch Dashboard",
 "time": { "from": "2024-10-27T23:00:00.000Z", "to": "2024-11-02T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "User",
    "label": "User",
    "query": {
     "query": "label_values(aw_watcher_window,user)"
    }
   },
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "label_values(aw_watcher_window{user=~\"$User\"},host)"
    }
   },
   {
    "name": "Categories",
    "label": "Categories",
    "query": {
     "query": "label_values(aw_watcher_window,category)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "Total active users the past 1 year",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by(user) (sum_over_time(aw_watcher_window[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "Active users in the selected time range",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "Active hosts in the selected time range",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "state-timeline",
   "description": "Watchers' Activity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "aw_watcher_afk", "legendFormat": "__auto" },
    { "expr": "aw_watcher_window", "legendFormat": "__auto" },
    { "expr": "aw_client_web", "legendFormat": "__auto" },
    { "expr": "aw_watcher_vscode", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "table",
   "description": "Total active hosts the past 1 year",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count by(host) (sum_over_time(aw_watcher_window[1y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Window", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Most Used Applications",
   "type": "piechart",
   "description": "Depicts the used applications in a pie form ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window{user=~\"$User\", host=~\"$Host\", category=~\"$Categories\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Window Titles",
   "type": "bargauge",
   "description": "Window Titles and their  total time spent",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window{user=~\"$User\", host=~\"$Host\", category=~\"$Categories\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Used Applications' Duration",
   "type": "gauge",
   "description": "Shows the used applications and their total duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window{user=~\"$User\", host=~\"$Host\", category=~\"$Categories\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Browser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Web Browser Traces",
   "type": "table",
   "description": "Traces of web browser urls",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum_over_time(aw_client_web[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Browser URLs",
   "type": "bargauge",
   "description": "Browser URLs and their time spent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum_over_time(aw_client_web[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Editor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top Editor Files",
   "type": "bargauge",
   "description": "Editor files and the time spent on them",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_vscode[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Editor Projects",
   "type": "bargauge",
   "description": "Editor projects and the time spent on them",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_vscode[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Editor Languages",
   "type": "piechart",
   "description": "Editor languages and their usage in the form of a donut",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_vscode[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Categories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window{host=~\"$Host\", user=~\"$User\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Categories",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window{user=~\"$User\", host=~\"$Host\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_window{host=~\"$Host\", user=~\"$User\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AFK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "AFK Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum_over_time(aw_watcher_afk{host=~\"$Host\", user=~\"$User\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}