{
 "title": "Prototype",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "User",
    "label": "User",
    "query": {
     "query": "label_values(aw_watcher_window,user)"
    }
   },
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "label_values(aw_watcher_window{user=~\"$User\"},host)"
    }
   },
   { "name": "Categories", "label": "Categories", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(sum by (user) ({__name__=~\"aw_watcher.*\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 3, "y": 1 },
     "targets": [
      {
       "expr": "count by(user) ({__name__=~\"aw_watcher.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "sum by(host) ({__name__=~\"aw_watcher.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Activity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(__name__) (aw_watcher_afk)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(__name__) (aw_watcher_window)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "count(count by (host) ({__name__=~\"aw_watcher.*\"}))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Window",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Most Used Applications",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum by(app) (aw_watcher_window{user=~\"$User\", host=~\"$Host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top Window Titles",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by(title) (aw_watcher_window{user=~\"$User\", host=~\"$Host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Most Used Applications' Duration",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by(app) (aw_watcher_window{user=~\"$User\", host=~\"$Host\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Browser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Top Browser Domains", "type": "bargauge", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    { "title": "Top Browser URLs", "type": "bargauge", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } }
   ]
  },
  {
   "title": "Editor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    { "title": "Top Editor Files", "type": "bargauge", "gridPos": { "h": 16, "w": 12, "x": 0, "y": 4 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    { "title": "Top Editor Projects", "type": "bargauge", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    { "title": "Top Editor Languages", "type": "bargauge", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } }
   ]
  },
  {
   "title": "Categories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(status) (aw_watcher_afk{host=~\"$Host\", user=~\"$User\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Categories",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by(status) (aw_watcher_afk{host=~\"$Host\", user=~\"$User\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "AFK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "AFK Timeline",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(status) (aw_watcher_afk{host=~\"$Host\", user=~\"$User\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AFK status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by(status) (aw_watcher_afk{host=~\"$Host\", user=~\"$User\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}