{
 "title": "Prototype",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "User",
    "label": "User",
    "query": {
     "query": "label_values(aw_watcher_window,user)"
    }
   },
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "label_values(aw_watcher_window{user=~\"$User\"},host)"
    }
   },
   {
    "name": "Categories",
    "label": "Categories",
    "query": {
     "query": "label_values(aw_watcher_window,category)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(sum by (user) ({__name__=~\"aw_watcher.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by (user) ({__name__=~\"aw_watcher.*\"} offset 6m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(host) ({__name__=~\"aw_watcher.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "aw_watcher_afk", "legendFormat": "__auto" },
    { "expr": "aw_watcher_window", "legendFormat": "__auto" },
    { "expr": "aw_client_web", "legendFormat": "__auto" },
    { "expr": "aw_watcher_vscode", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(count by (host) ({__name__=~\"aw_watcher.*\"}))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Window", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Most Used Applications",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(app) (aw_watcher_window{user=~\"$User\", host=~\"$Host\", category=~\"$Categories\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Window Titles",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(title) (aw_watcher_window{user=~\"$User\", host=~\"$Host\", category=~\"$Categories\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Used Applications' Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(app) (aw_watcher_window{user=~\"$User\", host=~\"$Host\", category=~\"$Categories\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Browser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Web Browser Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "aw_client_web", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Browser URLs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum by(url) (aw_client_web)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Editor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top Editor Files",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(file) (aw_watcher_vscode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Editor Projects",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(project) (aw_watcher_vscode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Editor Languages",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(language) (aw_watcher_vscode)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Categories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum  (aw_watcher_window{host=~\"$Host\", user=~\"$User\"}) by(category)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Categories",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(category) (aw_watcher_window{user=~\"$User\", host=~\"$Host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(aw_watcher_window{host=~\"$Host\", user=~\"$User\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AFK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "AFK Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(aw_watcher_afk{host=~\"$Host\", user=~\"$User\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}