services:
  aw-sync-agent:
    image: phrp5/aw-sync-agent:latest
    container_name: aw-sync-agent
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./config:/opt/config
    environment:
        - ACTIVITY_WATCH_URL=http://localhost:5600
        - PROMETHEUS_URL=http://localhost:9090
        - EXCLUDED_WATCHERS=aw-watcher-afk #Pipe seperated watchers to exclude
        - USER_ID=DemoUser
        - CRON=* * * * * #Cron expression to run the sync agent
