services:
  aw-sync-agent:
    image: phrp5/aw-sync-agent
    network_mode: "host"
    container_name: aw-sync-agent
    restart: unless-stopped
    volumes:
      - ./aw-sync-agent.yaml:/opt/aw-sync-agent/aw-sync-agent.yaml
