networks:
  monitoring:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=1y'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - "9090:9090"
#    deploy:
#      resources:
#        limits:
#          memory: 8g  # Set the maximum RAM (e.g., 4GB)
#        reservations:
#          memory: 4g  # Optional: Reserve minimum RAM (e.g., 2GB)
  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
#    deploy:
#      resources:
#        limits:
#          memory: 8g  # Set the maximum RAM (e.g., 4GB)
#        reservations:
#          memory: 4g  # Optional: Reserve minimum RAM (e.g., 2GB)
volumes:
  prom_data:
