name: Build and Package Release

on:
  release:
    types: [created]

jobs:
  build-and-package:
    name: Build and Package Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2' # Use your Go version

      # Cache Go modules
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Build aw-sync-agent for Linux
      - name: Build aw-sync-agent for Linux
        working-directory: aw-sync-agent
        run: |
          mkdir -p ../release/linux
          GOOS=linux GOARCH=amd64 go build -o ../release/linux/aw-sync-agent
          cp aw-sync-agent.yaml ../release/linux/

      # Build aw-sync-agent for Windows
      - name: Build aw-sync-agent for Windows
        working-directory: aw-sync-agent
        run: |
          mkdir -p ../release/windows
          GOOS=windows GOARCH=amd64 go build -o ../release/windows/aw-sync-agent.exe
          cp aw-sync-agent.yaml ../release/windows/

      # Package aw-sync-center
      - name: Package aw-sync-center
        run: |
          mkdir -p release/aw-sync-center
          cp -r aw-sync-center/* release/aw-sync-center/

      # Create separate ZIP files
      - name: Create ZIP files
        run: |
          cd release
          zip -r aw-sync-agent-linux.zip linux
          zip -r aw-sync-agent-windows.zip windows
          zip -r aw-sync-center.zip aw-sync-center

      # Combine files into aw-sync-suite.zip
      - name: Create aw-sync-suite.zip
        run: |
          cd release
          mkdir aw-sync-suite
          mkdir aw-sync-suite/aw-sync-agent
          cp -r linux aw-sync-suite/aw-sync-agent/
          cp -r windows aw-sync-suite/aw-sync-agent/
          cp -r aw-sync-center aw-sync-suite/
          zip -r aw-sync-suite.zip aw-sync-suite

      # Upload release assets
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/aw-sync-agent-linux.zip
          asset_name: aw-sync-agent-linux.zip
          asset_content_type: application/zip

      - name: Upload aw-sync-agent-windows.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/aw-sync-agent-windows.zip
          asset_name: aw-sync-agent-windows.zip
          asset_content_type: application/zip

      - name: Upload aw-sync-center.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/aw-sync-center.zip
          asset_name: aw-sync-center.zip
          asset_content_type: application/zip

      - name: Upload aw-sync-suite.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/aw-sync-suite.zip
          asset_name: aw-sync-suite.zip
          asset_content_type: application/zip
